version: "3"

services:
  client:
    build: .
    image: allania7med11/docker_start
    container_name: docker_start_container
    restart: always
    command: npm start
    volumes:
      - .:/client
      - /client/node_modules
    ports:
      - 3000:3000
